services:
  mariadb:
    image: mariadb:11
    restart: on-failure:10
    command: "--init-file /init.sql"
    environment:
      MARIADB_ROOT_PASSWORD: 12345
    volumes:
      - mariadb:/var/lib/mysql
      - ./maria-db-dev-init.sql:/init.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure:10
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-secrets:/etc/zookeeper/secrets
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: on-failure:10
    depends_on:
      - zookeeper
    volumes:
      - kafka-secrets:/etc/kafka/secrets
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  init-kafka:
    image: confluentinc/cp-kafka:latest
    restart: on-failure:10
    init: true
    depends_on:
      - kafka
    command: ["/bin/sh", "-c", "/kafka.sh"]
    volumes:
      - ./inits/kafka.sh:/kafka.sh

  clickhouse:
    image: clickhouse/clickhouse-server:22.2
    restart: on-failure:10
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: 123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: default
      CLICKHOUSE_UID: 0
      CLICKHOUSE_GID: 0
    volumes:
      - clickhouse-log:/var/log/clickhouse-server
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-db-dev-init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.12
    restart: on-failure:10
    environment:
      RABBITMQ_DEFAULT_USER: task
      RABBITMQ_DEFAULT_PASS: task_pwd
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:7.2
    restart: on-failure:10
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16
    restart: on-failure:10
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres-db-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 2

  dbgate:
    image: dbgate/dbgate:7.3.0
    restart: on-failure:10
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1,con2,con3,con4

      LABEL_con1: MariaDB
      SERVER_con1: mariadb
      USER_con1: root
      PASSWORD_con1: 12345
      PORT_con1: 3306
      ENGINE_con1: mariadb@dbgate-plugin-mysql

      LABEL_con2: ClickHouse
      USER_con2: admin
      PASSWORD_con2: 123
      URL_con2: http://clickhouse:8123
      ENGINE_con2: clickhouse@dbgate-plugin-clickhouse

      LABEL_con3: Redis
      SERVER_con3: redis
      ENGINE_con3: redis@dbgate-plugin-redis

      LABEL_con4: Postgres
      SERVER_con4: postgres
      USER_con4: postgres
      PASSWORD_con4: postgres
      PORT_con4: 5432
      ENGINE_con4: postgres@dbgate-plugin-postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.dbgate.rule=Host(`db.localhost`)
      - traefik.http.services.dbgate.loadbalancer.server.url=http://dbgate:3000

volumes:
  mariadb: {}
  kafka-secrets: {}
  kafka-data: {}
  zookeeper-secrets: {}
  zookeeper-data: {}
  zookeeper-log: {}
  clickhouse-data: {}
  clickhouse-log: {}
  rabbitmq-data: {}
  redis-data: {}
  postgres: {}
  dbgate-data: {}
