services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.147.0
    restart: on-failure:10
    command:
      - -retentionPeriod=1d
    volumes:
      - victoriametrics-data:/victoria-metrics-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.metrics.rule=Host(`metrics.localhost`)
      - traefik.http.services.victoriametrics.loadbalancer.server.url=http://victoriametrics:8428
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 2

  victorialogs:
    image: victoriametrics/victoria-logs:v1.52.0
    restart: on-failure:10
    command:
      - -retentionPeriod=1d
      - -retention.maxDiskSpaceUsageBytes=100MiB
      - -insert.maxLineSizeBytes=1MiB
    volumes:
      - victorialogs-data:/victoria-logs-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.logs.rule=Host(`logs.localhost`)
      - traefik.http.services.victorialogs.loadbalancer.server.url=http://victorialogs:9428
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 2

  victoriatraces:
    image: victoriametrics/victoria-traces:v0.11.0
    restart: on-failure:10
    command:
      - -retentionPeriod=1d
      - -retention.maxDiskSpaceUsageBytes=100MiB
    volumes:
      - victoriatraces-data:/victoria-traces-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.traces.rule=Host(`traces.localhost`)
      - traefik.http.services.victoriatraces.loadbalancer.server.url=http://victoriatraces:10428
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 2

  grafana:
    image: grafana/grafana-oss:13.0.2
    restart: on-failure:10
    user: 0:0
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    environment:
      GF_INSTALL_PLUGINS: victoriametrics-logs-datasource
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SERVER_ROOT_URL: http://grafana.localhost
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.services.grafana.loadbalancer.server.url=http://grafana:3000
    depends_on:
      - victoriametrics
      - victorialogs
      - victoriatraces
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 2

  alloy:
    image: grafana/alloy:v1.19.2
    restart: on-failure:10
    user: 0:0
    hostname: localhost-buttoners
    depends_on:
      - victoriametrics
      - victorialogs
      - victoriatraces
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - alloy-data:/var/lib/alloy/data
      - ./configs/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.alloy.rule=Host(`alloy.localhost`)
      - traefik.http.services.alloy.loadbalancer.server.url=http://alloy:12345
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 2

volumes:
  victoriametrics-data: {}
  victorialogs-data: {}
  victoriatraces-data: {}
  alloy-data: {}
  grafana-data: {}
