openapi: 3.0.0

info:
  title: Notification service
  version: 0.0.0

servers:
  - url: http://localhost:8080/

security:
  - headerAuth: []

paths:
  /api/v1/new:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  format: int64
                kind:
                  type: string
                level:
                  type: string
                title:
                  type: string
                body:
                  type: string
                created:
                  type: string
                  format: date-time
              required:
                - user_id
                - kind
                - level
                - title
                - body
                - created

      responses:
        204:
          description: Успешное создание
        400:
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Токен доступа не предоставлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Серверная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/list:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  format: int64
              required:
                - user_id

      responses:
        200:
          description: Список уведомлений
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      $ref: "#/components/schemas/NotificationData"
        400:
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Токен доступа не предоставлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Серверная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/read:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  format: int64
                id:
                  type: integer
                  format: int64
              required:
                - user_id

      responses:
        204:
          description: Отмечено прочитанным
        400:
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Токен доступа не предоставлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Доступ запрещен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Данные не найдены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Серверная ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ErrorResponse:
      type: object
      description: Данные ошибки
      properties:
        code:
          type: string
          description: Внутренний код ошибки
        details:
          type: string
          description: Детальные данные ошибки
      required:
        - code
    NotificationData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        kind:
          type: string
        level:
          type: string
        title:
          type: string
        body:
          type: string
        created:
          type: string
          format: date-time
      required:
        - id
        - kind
        - level
        - title
        - body
        - created

  securitySchemes:
    headerAuth:
      name: Authorization
      in: header
      type: apiKey
