{
 "title": "Buttoners service legacy",
 "tags": [ "buttoners" ],
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "service",
    "query": "label_values(process_cpu_seconds_total{service=~\"legacy\"}, service)"
   },
   {
    "name": "pod",
    "query": "label_values(process_cpu_seconds_total{service=~\"$service\"}, pod)"
   },
   { "name": "quantile", "query": ".50,.80,.95,.99" },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Входящий RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_grpc_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr)",
     "legendFormat": "grpc server => {{server_addr}}"
    },
    {
     "expr": "sum(rate(buttoners_http_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr)",
     "legendFormat": "http server => {{server_addr}}"
    }
   ]
  },
  {
   "title": "Исходящий RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_grpc_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "grpc client => {{target_host}}"
    },
    {
     "expr": "sum(rate(buttoners_http_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "http client => {{target_host}}"
    },
    {
     "expr": "sum(rate(buttoners_redis_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "redis => {{target_host}}"
    }
   ]
  },
  {
   "title": "Входящий MPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_queue_reader_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr)",
     "legendFormat": "queue reader => {{server_addr}}"
    }
   ]
  },
  {
   "title": "Исходящий MPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_queue_writer_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "queue writer => {{target_host}}"
    }
   ]
  },
  {
   "title": "Входящие задержки",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(buttoners_grpc_server_handle_seconds_bucket{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr, le))",
     "legendFormat": "grpc server => {{server_addr}}"
    },
    {
     "expr": "histogram_quantile($quantile, sum(rate(buttoners_http_server_handle_seconds_bucket{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr, le))",
     "legendFormat": "http server => {{server_addr}}"
    }
   ]
  },
  {
   "title": "Исходящие задержки",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(buttoners_grpc_client_handle_seconds_bucket{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host, le))",
     "legendFormat": "grpc client => {{target_host}}"
    },
    {
     "expr": "histogram_quantile($quantile, sum(rate(buttoners_http_client_handle_seconds_bucket{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host, le))",
     "legendFormat": "http client => {{target_host}}"
    },
    {
     "expr": "histogram_quantile($quantile, sum(rate(buttoners_redis_handle_seconds_bucket{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host, le))",
     "legendFormat": "redis => {{target_host}}"
    }
   ]
  },
  {
   "title": "Входящие задержки очередей",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(buttoners_queue_reader_handle_seconds_bucket{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr, le))",
     "legendFormat": "queue reader => {{server_addr}}"
    }
   ]
  },
  {
   "title": "Исходящие задержки очередей",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(buttoners_queue_writer_handle_seconds_bucket{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host, le))",
     "legendFormat": "queue writer => {{target_host}}"
    }
   ]
  },
  {
   "title": "Входящий error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_grpc_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status!=\"OK\"}[$__rate_interval])) by (server_addr) or vector(0)/ sum(rate(buttoners_grpc_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr)",
     "legendFormat": "grpc server => {{server_addr}}"
    },
    {
     "expr": "sum(rate(buttoners_http_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status=~\"4\\\\d{2}\"}[$__rate_interval])) by (server_addr) or vector(0)/ sum(rate(buttoners_http_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr)",
     "legendFormat": "http server 4xx => {{server_addr}}"
    },
    {
     "expr": "sum(rate(buttoners_http_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status=~\"5\\\\d{2}\"}[$__rate_interval])) by (server_addr) or vector(0)/ sum(rate(buttoners_http_server_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr)",
     "legendFormat": "http server 5xx => {{server_addr}}"
    }
   ]
  },
  {
   "title": "Исходящий error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_grpc_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status!=\"OK\"}[$__rate_interval])) by (target_host) or vector(0)/ sum(rate(buttoners_grpc_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "grpc client => {{target_host}}"
    },
    {
     "expr": "sum(rate(buttoners_http_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status=~\"4\\\\d{2}\"}[$__rate_interval])) by (target_host) or vector(0)/ sum(rate(buttoners_http_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "http client 4xx => {{target_host}}"
    },
    {
     "expr": "sum(rate(buttoners_http_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status=~\"5\\\\d{2}\"}[$__rate_interval])) by (target_host) or vector(0)/ sum(rate(buttoners_http_client_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "http client 5xx => {{target_host}}"
    },
    {
     "expr": "sum(rate(buttoners_redis_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status=\"err\"}[$__rate_interval])) by (target_host) or vector(0)/ sum(rate(buttoners_redis_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "redis => {{target_host}}"
    }
   ]
  },
  {
   "title": "Входящий error rate очередей",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_queue_reader_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status=\"err\"}[$__rate_interval])) by (server_addr) or vector(0)/ sum(rate(buttoners_queue_reader_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (server_addr)",
     "legendFormat": "queue reader => {{server_addr}}"
    }
   ]
  },
  {
   "title": "Исходящий error rate очередей",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(buttoners_queue_writer_handle_seconds_count{service=~\"$service\", pod=~\"$pod\", status=\"err\"}[$__rate_interval])) by (target_host) or vector(0)/ sum(rate(buttoners_queue_writer_handle_seconds_count{service=~\"$service\", pod=~\"$pod\"}[$__rate_interval])) by (target_host)",
     "legendFormat": "queue writer => {{target_host}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "service: ($service) pod: ($pod)"
    }
   ]
  }
 ]
}