[[boards]]
name = "Buttoners ALL"
uid = "gg-main"
output_file = "deployments/dashboards/gg-main.json"
service_filter = ".+"

[[boards]]
name = "Buttoners service auth"
uid = "gg-auth"
output_file = "deployments/dashboards/gg-auth.json"
service_filter = "auth"

[[boards]]
name = "Buttoners service gate"
uid = "gg-gate"
output_file = "deployments/dashboards/gg-gate.json"
service_filter = "gate"

[[boards]]
name = "Buttoners service handler"
uid = "gg-handler"
output_file = "deployments/dashboards/gg-handler.json"
service_filter = "handler"

[[boards]]
name = "Buttoners service legacy"
uid = "gg-legacy"
output_file = "deployments/dashboards/gg-legacy.json"
service_filter = "legacy"

[[boards]]
name = "Buttoners service log"
uid = "gg-log"
output_file = "deployments/dashboards/gg-log.json"
service_filter = "log"

[[boards]]
name = "Buttoners service notification"
uid = "gg-notification"
output_file = "deployments/dashboards/gg-notification.json"
service_filter = "notification"

[[boards]]
name = "Buttoners service worker"
uid = "gg-worker"
output_file = "deployments/dashboards/gg-worker.json"
service_filter = "worker"
