data_dir: /var/lib/vector

sources:
  docker:
    type: docker_logs

transforms:
  docker_filter:
    type: filter
    inputs:
      - docker_parser
    condition: .label."com.docker.compose.project" == "buttoners"
  docker_parser:
    type: remap
    inputs:
      - docker
    source: |
      .host = "buttoners stand"
      .job = "dockerlogs"

      message, err = parse_json(.message)
      if (err == null) {
        if exists(message.trace_id) {
          .trace_id = message.trace_id
        }
        if exists(message.service_name) {
          .service_name = message.service_name
        }
      }

sinks:
  http_docker:
    type: http
    inputs:
      - docker_filter
    uri: http://victorialogs:9428/insert/jsonline
    encoding:
      codec: json
    framing:
      method: newline_delimited
    compression: gzip
    healthcheck:
      enabled: false
    request:
      headers:
        AccountID: "0"
        ProjectID: "0"
        VL-Stream-Fields: source_type,host,container_name,label.com.docker.compose.service
        VL-Msg-Field: message
        VL-Time-Field: timestamp
